# React Native ve native modüllerin gerekli dosyalarını dahil edin
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# React Native izinleri için gerekli olan podları dahil edin
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"

# React Native core kütüphanesini yalnızca tek bir kaynaktan dahil edin
# `React-Core`'u sadece bir kez dahil etmelisiniz, bu yüzden aşağıdaki satırda tek bir yol kullanacağız.
pod 'React-Core', :path => '../node_modules/react-native/'

# iOS platform versiyonunu belirleyin
platform :ios, '14.0'

# React Native projesini hazırlayın
prepare_react_native_project!

# Flipper yapılandırması (gerekirse devre dışı bırakılabilir)
#flipper_config = FlipperConfiguration.disabled

# `USE_FRAMEWORKS` ortam değişkenine göre frameworks kullanımı yapılandırın
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Aktuel hedefi için pod'ları dahil edin
target 'Aktuel' do
  # Native modülleri dahil et
  config = use_native_modules!

  # Çevresel değişkenlere göre bayraklar (flags) ayarla
  flags = get_default_flags()

  # React Native yapılandırmasını yapın
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes, varsayılan olarak etkin. Eğer kullanmak istemiyorsanız false yapabilirsiniz.
    :hermes_enabled => false,
    # Fabric henüz etkin değil.
    :fabric_enabled => false,
    # Flipper yapılandırmasını yapın (Flipper kullanmak istemiyorsanız devre dışı bırakabilirsiniz).
    #:flipper_configuration => flipper_config,
    # Uygulama yolu
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Aktuel test hedefi için pod'ları dahil et
  target 'AktuelTests' do
    inherit! :complete
    # Testler için gerekli pod'ları buraya ekleyebilirsiniz
  end

  # Post-install işlemleri
  post_install do |installer|
    react_native_post_install(
      installer,
      # Eğer Mac Catalyst desteğine ihtiyacınız yoksa bunu false yapabilirsiniz.
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      if target.name == "React-Core.common-RCTI18nStrings"
        # https://github.com/facebook/react-native/issues/43610#issuecomment-2017636169                                                                                                                                   
        target.remove_from_project
      end
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET' # inherit                                                                                                                                             
      end
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  
    # Aşağıdaki satırı kaldırın veya yoruma alın
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  
end
