const mainColor ={
    black: '#000000',
    white: '#FFFFFF',
    blue: '#007bff',
    red: '#62b7ff',
    yellow: '#fcd155',
    green: '#6beb76',
    orange: '#fbb550',
    buttongray: '#f8f8f8',
    buttonblue: '#007BFF',
    gray: '#5f5e5e',
    textinputgray: '#F4F4F4',
    islembuttongray: '#dbdbdb',
    placeholderTextColor: '#000000',
    textInputBg: '#ededed',
    ustmenubggray: '#f2f2f2',
};

export const colors ={
    black:mainColor.black,
    white:mainColor.white,
    blue:mainColor.blue,
    red:mainColor.red,
    yellow:mainColor.yellow,
    green:mainColor.green,
    orange:mainColor.orange,
    buttongray:mainColor.buttongray,
    buttonblue:mainColor.buttonblue,
    gray:mainColor.gray,
    textinputgray:mainColor.textinputgray,
    islembuttongray:mainColor.islembuttongray,
    placeholderTextColor:mainColor.placeholderTextColor,
    textInputBg:mainColor.textInputBg,
    ustmenubggray:mainColor.ustmenubggray,
};